[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --break-system-packages -r linemovement/requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python3 app.py"
