[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install requests>=2.28.0 schedule>=1.2.0 flask>=2.3.0 pandas>=2.0.0 gunicorn>=20.1.0 pytz>=2023.3"
]

[phases.build]
cmds = []

[start]
cmd = "cd /app && /opt/venv/bin/python3 app.py"
