[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install requests>=2.28.0",
  "/opt/venv/bin/pip install schedule>=1.2.0", 
  "/opt/venv/bin/pip install flask>=2.3.0",
  "/opt/venv/bin/pip install pandas>=2.0.0",
  "/opt/venv/bin/pip install gunicorn>=20.1.0",
  "/opt/venv/bin/pip install pytz>=2023.3",
  "/opt/venv/bin/pip list"
]

[phases.build]
cmds = []

[start]
cmd = "cd /app && /opt/venv/bin/python app.py"
