[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install --break-system-packages -r linemovement/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 app.py"
