[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r linemovement/requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python app.py"
